# Generated by Django 5.2.12 on 2026-05-06 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_favorite_product_favorite_products_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='products',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.genre')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.platform')),
            ],
        ),
        migrations.AddField(
            model_name='favorite',
            name='games',
            field=models.ManyToManyField(to='shop.game'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.game')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
