# Generated by Django 5.2.12 on 2026-05-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_game_platform_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(blank=True, to='shop.platform'),
        ),
    ]
